name: Build and Push Docker Image

# ¿Cuándo se ejecuta? Cada vez que haces push a la rama main
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # GitHub nos presta un servidor Linux gratis
    
    steps:
    # 1. Descargar tu código en el servidor de GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Iniciar sesión en Docker Hub (usando los secretos que configuraste)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Construir y Subir la imagen automáticamente
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        # Aquí usamos 'latest' para que siempre se actualice la última versión
        tags: johnal22/contentful-hello-world:latest